import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { getToken } from '../services/authService';

import { API_URL } from '../services/api';

interface ProfitSummary {
  today: {
    revenue: number;
    profit: number;
    sales_count: number;
  };
  week: {
    revenue: number;
    profit: number;
    sales_count: number;
  };
  month: {
    revenue: number;
    profit: number;
    sales_count: number;
  };
}

const ProfitReports: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [loadingReports, setLoadingReports] = useState<{[key: string]: boolean}>({});
  const [summary, setSummary] = useState<ProfitSummary | null>(null);
  const [message, setMessage] = useState('');
  
  // Daily report
  const [dailyDate, setDailyDate] = useState(new Date().toISOString().split('T')[0]);
  
  // Weekly report
  const [weeklyEndDate, setWeeklyEndDate] = useState(new Date().toISOString().split('T')[0]);
  
  // Monthly report
  const [monthlyYear, setMonthlyYear] = useState(new Date().getFullYear());
  const [monthlyMonth, setMonthlyMonth] = useState(new Date().getMonth() + 1);
  
  // Yearly report
  const [yearlyYear, setYearlyYear] = useState(new Date().getFullYear());

  useEffect(() => {
    fetchSummary();
  }, []);

  const fetchSummary = async () => {
    try {
      // Fetch today, weekly, and monthly stats from the new endpoints
      const [todayResponse, weeklyResponse, monthlyResponse] = await Promise.all([
        axios.get(`${API_URL}/dashboard/today-stats`, {
          headers: { Authorization: `Bearer ${getToken()}` }
        }),
        axios.get(`${API_URL}/dashboard/weekly-stats`, {
          headers: { Authorization: `Bearer ${getToken()}` }
        }),
        axios.get(`${API_URL}/dashboard/monthly-stats`, {
          headers: { Authorization: `Bearer ${getToken()}` }
        })
      ]);
      
      // Transform the data to match the expected format
      const summaryData = {
        today: {
          revenue: todayResponse.data.sales_total || 0,
          profit: todayResponse.data.total_profit || 0,
          sales_count: todayResponse.data.sales_count || 0
        },
        week: {
          revenue: weeklyResponse.data.sales_total || 0,
          profit: weeklyResponse.data.total_profit || 0,
          sales_count: weeklyResponse.data.sales_count || 0
        },
        month: {
          revenue: monthlyResponse.data.sales_total || 0,
          profit: monthlyResponse.data.total_profit || 0,
          sales_count: monthlyResponse.data.sales_count || 0
        }
      };
      
      setSummary(summaryData);
    } catch (error: any) {
      console.error('Failed to fetch summary:', error);
      // Set default values on error
      setSummary({
        today: { revenue: 0, profit: 0, sales_count: 0 },
        week: { revenue: 0, profit: 0, sales_count: 0 },
        month: { revenue: 0, profit: 0, sales_count: 0 }
      });
    }
  };

  const downloadReport = async (endpoint: string, filename: string, reportType: string) => {
    setLoadingReports(prev => ({ ...prev, [reportType]: true }));
    setMessage('');
    
    try {
      const response = await axios.get(`${API_URL}${endpoint}`, {
        headers: { Authorization: `Bearer ${getToken()}` }
      });
      
      // Create a text-based report
      const reportData = response.data;
      let reportContent = '';
      
      if (reportType === 'hub-profits') {
        reportContent = generateHubProfitsReport(reportData);
      } else {
        // For other reports, create a simple JSON report
        reportContent = JSON.stringify(reportData, null, 2);
      }
      
      // Create download link for text file
      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', filename.replace('.pdf', '.txt'));
      document.body.appendChild(link);
      link.click();
      link.remove();
      
      setMessage('✅ Report downloaded successfully!');
    } catch (error: any) {
      setMessage(`❌ Error: ${error.response?.data?.detail || error.message}`);
    } finally {
      setLoadingReports(prev => ({ ...prev, [reportType]: false }));
    }
  };

  const generateHubProfitsReport = (data: any) => {
    const { report_title, generated_at, generated_by, company_name, hub_profits, summary } = data;
    
    return `
${company_name.toUpperCase()}
${report_title}
Generated: ${new Date(generated_at).toLocaleString()}
Generated by: ${generated_by}

═══════════════════════════════════════════════════════════════

PROFIT SUMMARY
═══════════════════════════════════════════════════════════════
Total Profit: ₵${summary.total_profit.toFixed(2)}
Products Profit: ₵${summary.products_profit.toFixed(2)}
Swapping Profit: ₵${summary.swapping_profit.toFixed(2)}
Repairs Profit: ₵${summary.repairs_profit.toFixed(2)}

═══════════════════════════════════════════════════════════════

DETAILED BREAKDOWN
═══════════════════════════════════════════════════════════════

PRODUCTS HUB:
- Revenue: ₵${hub_profits.products_hub?.revenue?.toFixed(2) || '0.00'}
- Cost: ₵${hub_profits.products_hub?.cost?.toFixed(2) || '0.00'}
- Profit: ₵${hub_profits.products_hub?.profit?.toFixed(2) || '0.00'}

SWAPPING HUB:
- Profit: ₵${hub_profits.swapping_hub?.profit?.toFixed(2) || '0.00'}
- Note: ${hub_profits.swapping_hub?.note || 'Profit from resold phones'}

REPAIRER HUB:
- Service Revenue: ₵${hub_profits.repairer_hub?.service_revenue?.toFixed(2) || '0.00'}
- Items Revenue: ₵${hub_profits.repairer_hub?.items_revenue?.toFixed(2) || '0.00'}
- Items Profit: ₵${hub_profits.repairer_hub?.items_profit?.toFixed(2) || '0.00'}
- Total Profit: ₵${hub_profits.repairer_hub?.total_profit?.toFixed(2) || '0.00'}

═══════════════════════════════════════════════════════════════

END OF REPORT
═══════════════════════════════════════════════════════════════
    `.trim();
  };

  const handleDailyReport = () => {
    downloadReport(
      `/profit-reports/daily?date=${dailyDate}`,
      `Daily_Profit_Report_${dailyDate}.pdf`,
      'daily'
    );
  };

  const handleWeeklyReport = () => {
    downloadReport(
      `/profit-reports/weekly?end_date=${weeklyEndDate}`,
      `Weekly_Profit_Report_${weeklyEndDate}.pdf`,
      'weekly'
    );
  };

  const handleMonthlyReport = () => {
    downloadReport(
      `/profit-reports/monthly?year=${monthlyYear}&month=${monthlyMonth}`,
      `Monthly_Profit_Report_${monthlyYear}_${monthlyMonth}.pdf`,
      'monthly'
    );
  };

  const handleYearlyReport = () => {
    downloadReport(
      `/profit-reports/yearly?year=${yearlyYear}`,
      `Yearly_Profit_Report_${yearlyYear}.pdf`,
      'yearly'
    );
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="mx-6 space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Profit Reports</h1>
          <p className="text-gray-600 mt-1">Generate and download comprehensive profit reports (Manager Only)</p>
        </div>

        {message && (
          <div className={`p-4 rounded-lg ${message.includes('✅') ? 'bg-green-50 text-green-800' : 'bg-red-50 text-red-800'}`}>
            {message}
          </div>
        )}

        {/* Quick Summary */}
        {summary ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Today */}
            <div className="bg-gradient-to-br from-blue-50 to-indigo-100 rounded-2xl border border-blue-200 p-6 shadow-sm hover:shadow-md transition-all duration-300">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-10 h-10 rounded-lg bg-blue-500 flex items-center justify-center text-white text-lg">
                  📅
                </div>
                <h3 className="text-lg font-semibold text-blue-900">Today's Performance</h3>
              </div>
              <div className="space-y-2.5">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-blue-700">Revenue:</span>
                  <span className="text-lg font-bold text-blue-900">₵{summary?.today?.revenue?.toFixed(2) || '0.00'}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-blue-700">Profit:</span>
                  <span className="text-lg font-bold text-blue-900">₵{summary?.today?.profit?.toFixed(2) || '0.00'}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-blue-700">Sales:</span>
                  <span className="text-lg font-bold text-blue-900">{summary?.today?.sales_count || 0}</span>
                </div>
              </div>
            </div>

            {/* This Week */}
            <div className="bg-gradient-to-br from-emerald-50 to-teal-100 rounded-2xl border border-emerald-200 p-6 shadow-sm hover:shadow-md transition-all duration-300">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-10 h-10 rounded-lg bg-emerald-500 flex items-center justify-center text-white text-lg">
                  📊
                </div>
                <h3 className="text-lg font-semibold text-emerald-900">This Week</h3>
              </div>
              <div className="space-y-2.5">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-emerald-700">Revenue:</span>
                  <span className="text-lg font-bold text-emerald-900">₵{summary?.week?.revenue?.toFixed(2) || '0.00'}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-emerald-700">Profit:</span>
                  <span className="text-lg font-bold text-emerald-900">₵{summary?.week?.profit?.toFixed(2) || '0.00'}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-emerald-700">Sales:</span>
                  <span className="text-lg font-bold text-emerald-900">{summary?.week?.sales_count || 0}</span>
                </div>
              </div>
            </div>

            {/* This Month */}
            <div className="bg-gradient-to-br from-purple-50 to-pink-100 rounded-2xl border border-purple-200 p-6 shadow-sm hover:shadow-md transition-all duration-300">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-10 h-10 rounded-lg bg-purple-500 flex items-center justify-center text-white text-lg">
                  📈
                </div>
                <h3 className="text-lg font-semibold text-purple-900">This Month</h3>
              </div>
              <div className="space-y-2.5">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-purple-700">Revenue:</span>
                  <span className="text-lg font-bold text-purple-900">₵{summary?.month?.revenue?.toFixed(2) || '0.00'}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-purple-700">Profit:</span>
                  <span className="text-lg font-bold text-purple-900">₵{summary?.month?.profit?.toFixed(2) || '0.00'}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-purple-700">Sales:</span>
                  <span className="text-lg font-bold text-purple-900">{summary?.month?.sales_count || 0}</span>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Loading placeholders */}
            {[1, 2, 3].map((i) => (
              <div key={i} className="bg-gray-100 rounded-2xl border border-gray-200 p-6 animate-pulse">
                <div className="flex items-center gap-2 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-gray-300"></div>
                  <div className="h-6 bg-gray-300 rounded w-32"></div>
                </div>
                <div className="space-y-2.5">
                  <div className="flex justify-between items-center">
                    <div className="h-4 bg-gray-300 rounded w-16"></div>
                    <div className="h-6 bg-gray-300 rounded w-20"></div>
                  </div>
                  <div className="flex justify-between items-center">
                    <div className="h-4 bg-gray-300 rounded w-12"></div>
                    <div className="h-6 bg-gray-300 rounded w-20"></div>
                  </div>
                  <div className="flex justify-between items-center">
                    <div className="h-4 bg-gray-300 rounded w-10"></div>
                    <div className="h-6 bg-gray-300 rounded w-8"></div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* System Reports Section */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">📊 System Reports</h2>
          <p className="text-gray-600 mb-6">Comprehensive system-wide reports and analytics</p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {/* Hub Profits Report */}
            <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-4 border border-blue-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-lg bg-blue-100 flex items-center justify-center text-xl">
                  🏪
                </div>
                <div>
                  <h3 className="font-semibold text-blue-900">Hub Profits</h3>
                  <p className="text-xs text-blue-600">All hubs breakdown</p>
                </div>
              </div>
              <button
                onClick={() => downloadReport('/dashboard/hub-profits-report', 'Hub_Profits_Report.txt', 'hub-profits')}
                disabled={loadingReports['hub-profits']}
                className="w-full bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:bg-gray-300 transition-all"
              >
                {loadingReports['hub-profits'] ? '⏳ Generating...' : '📥 Download'}
              </button>
            </div>

            {/* Sales Analytics */}
            <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-xl p-4 border border-green-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-lg bg-green-100 flex items-center justify-center text-xl">
                  💰
                </div>
                <div>
                  <h3 className="font-semibold text-green-900">Sales Analytics</h3>
                  <p className="text-xs text-green-600">Sales performance</p>
                </div>
              </div>
              <button
                onClick={() => downloadReport('/analytics/sales', 'Sales_Analytics_Report.pdf', 'sales-analytics')}
                disabled={loadingReports['sales-analytics']}
                className="w-full bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:bg-gray-300 transition-all"
              >
                {loadingReports['sales-analytics'] ? '⏳ Generating...' : '📥 Download'}
              </button>
            </div>

            {/* Inventory Report */}
            <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-xl p-4 border border-purple-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-lg bg-purple-100 flex items-center justify-center text-xl">
                  📦
                </div>
                <div>
                  <h3 className="font-semibold text-purple-900">Inventory Report</h3>
                  <p className="text-xs text-purple-600">Stock analysis</p>
                </div>
              </div>
              <button
                onClick={() => downloadReport('/analytics/inventory', 'Inventory_Report.pdf', 'inventory')}
                disabled={loadingReports['inventory']}
                className="w-full bg-purple-500 hover:bg-purple-600 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:bg-gray-300 transition-all"
              >
                {loadingReports['inventory'] ? '⏳ Generating...' : '📥 Download'}
              </button>
            </div>

            {/* Customer Analytics */}
            <div className="bg-gradient-to-br from-orange-50 to-red-50 rounded-xl p-4 border border-orange-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-lg bg-orange-100 flex items-center justify-center text-xl">
                  👥
                </div>
                <div>
                  <h3 className="font-semibold text-orange-900">Customer Analytics</h3>
                  <p className="text-xs text-orange-600">Customer insights</p>
                </div>
              </div>
              <button
                onClick={() => downloadReport('/analytics/customers', 'Customer_Analytics_Report.pdf', 'customer-analytics')}
                disabled={loadingReports['customer-analytics']}
                className="w-full bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:bg-gray-300 transition-all"
              >
                {loadingReports['customer-analytics'] ? '⏳ Generating...' : '📥 Download'}
              </button>
            </div>

            {/* Repair Analytics */}
            <div className="bg-gradient-to-br from-teal-50 to-cyan-50 rounded-xl p-4 border border-teal-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-lg bg-teal-100 flex items-center justify-center text-xl">
                  🔧
                </div>
                <div>
                  <h3 className="font-semibold text-teal-900">Repair Analytics</h3>
                  <p className="text-xs text-teal-600">Repair performance</p>
                </div>
              </div>
              <button
                onClick={() => downloadReport('/repairs/stats/hub', 'Repair_Analytics_Report.pdf', 'repair-analytics')}
                disabled={loadingReports['repair-analytics']}
                className="w-full bg-teal-500 hover:bg-teal-600 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:bg-gray-300 transition-all"
              >
                {loadingReports['repair-analytics'] ? '⏳ Generating...' : '📥 Download'}
              </button>
            </div>

            {/* Pending Resales */}
            <div className="bg-gradient-to-br from-yellow-50 to-amber-50 rounded-xl p-4 border border-yellow-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-lg bg-yellow-100 flex items-center justify-center text-xl">
                  ⏳
                </div>
                <div>
                  <h3 className="font-semibold text-yellow-900">Pending Resales</h3>
                  <p className="text-xs text-yellow-600">Swap status report</p>
                </div>
              </div>
              <button
                onClick={() => downloadReport('/reports/pending-resales-detailed', 'Pending_Resales_Report.pdf', 'pending-resales')}
                disabled={loadingReports['pending-resales']}
                className="w-full bg-yellow-500 hover:bg-yellow-600 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:bg-gray-300 transition-all"
              >
                {loadingReports['pending-resales'] ? '⏳ Generating...' : '📥 Download'}
              </button>
            </div>
          </div>
        </div>

        {/* Profit Reports Section */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">💰 Profit Reports</h2>
          <p className="text-gray-600 mb-6">Detailed profit analysis by time period</p>
          
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Daily Report */}
          <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-6 border border-blue-100 shadow-sm hover:shadow-md transition-all duration-300">
            <div className="flex items-center gap-3 mb-5">
              <div className="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center text-2xl">
                📅
              </div>
              <div>
                <h2 className="text-lg font-semibold text-blue-900">Daily Report</h2>
                <p className="text-sm text-blue-600">Single day profit analysis</p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-blue-800 mb-2">Select Date</label>
                <input
                  type="date"
                  value={dailyDate}
                  onChange={(e) => setDailyDate(e.target.value)}
                  className="w-full bg-white/80 border border-blue-200 rounded-xl p-2.5 text-gray-700 focus:ring-2 focus:ring-blue-300 focus:border-transparent transition"
                />
              </div>
              <button
                onClick={handleDailyReport}
                disabled={loading}
                className="w-full bg-blue-500 hover:bg-blue-600 text-white px-6 py-2.5 rounded-xl font-medium disabled:bg-gray-300 transition-all duration-200 shadow-sm hover:shadow-md"
              >
                {loading ? 'Generating...' : '📥 Download Daily Report'}
              </button>
            </div>
          </div>

          {/* Weekly Report */}
          <div className="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border border-emerald-100 shadow-sm hover:shadow-md transition-all duration-300">
            <div className="flex items-center gap-3 mb-5">
              <div className="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center text-2xl">
                📊
              </div>
              <div>
                <h2 className="text-lg font-semibold text-emerald-900">Weekly Report</h2>
                <p className="text-sm text-emerald-600">Last 7 days profit analysis</p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-emerald-800 mb-2">End Date</label>
                <input
                  type="date"
                  value={weeklyEndDate}
                  onChange={(e) => setWeeklyEndDate(e.target.value)}
                  className="w-full bg-white/80 border border-emerald-200 rounded-xl p-2.5 text-gray-700 focus:ring-2 focus:ring-emerald-300 focus:border-transparent transition"
                />
                <p className="text-xs text-emerald-600 mt-1.5">Report includes 7 days ending on this date</p>
              </div>
              <button
                onClick={handleWeeklyReport}
                disabled={loading}
                className="w-full bg-emerald-500 hover:bg-emerald-600 text-white px-6 py-2.5 rounded-xl font-medium disabled:bg-gray-300 transition-all duration-200 shadow-sm hover:shadow-md"
              >
                {loading ? 'Generating...' : '📥 Download Weekly Report'}
              </button>
            </div>
          </div>

          {/* Monthly Report */}
          <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-2xl p-6 border border-purple-100 shadow-sm hover:shadow-md transition-all duration-300">
            <div className="flex items-center gap-3 mb-5">
              <div className="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center text-2xl">
                📈
              </div>
              <div>
                <h2 className="text-lg font-semibold text-purple-900">Monthly Report</h2>
                <p className="text-sm text-purple-600">Full month profit analysis</p>
              </div>
            </div>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium text-purple-800 mb-2">Month</label>
                  <select
                    value={monthlyMonth}
                    onChange={(e) => setMonthlyMonth(parseInt(e.target.value))}
                    className="w-full bg-white/80 border border-purple-200 rounded-xl p-2.5 text-gray-700 focus:ring-2 focus:ring-purple-300 focus:border-transparent transition"
                  >
                    <option value={1}>January</option>
                    <option value={2}>February</option>
                    <option value={3}>March</option>
                    <option value={4}>April</option>
                    <option value={5}>May</option>
                    <option value={6}>June</option>
                    <option value={7}>July</option>
                    <option value={8}>August</option>
                    <option value={9}>September</option>
                    <option value={10}>October</option>
                    <option value={11}>November</option>
                    <option value={12}>December</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-purple-800 mb-2">Year</label>
                  <input
                    type="number"
                    value={monthlyYear}
                    onChange={(e) => setMonthlyYear(parseInt(e.target.value))}
                    className="w-full bg-white/80 border border-purple-200 rounded-xl p-2.5 text-gray-700 focus:ring-2 focus:ring-purple-300 focus:border-transparent transition"
                    min={2020}
                    max={2030}
                  />
                </div>
              </div>
              <button
                onClick={handleMonthlyReport}
                disabled={loading}
                className="w-full bg-purple-500 hover:bg-purple-600 text-white px-6 py-2.5 rounded-xl font-medium disabled:bg-gray-300 transition-all duration-200 shadow-sm hover:shadow-md"
              >
                {loading ? 'Generating...' : '📥 Download Monthly Report'}
              </button>
            </div>
          </div>

          {/* Yearly Report */}
          <div className="bg-gradient-to-br from-amber-50 to-orange-50 rounded-2xl p-6 border border-amber-100 shadow-sm hover:shadow-md transition-all duration-300">
            <div className="flex items-center gap-3 mb-5">
              <div className="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center text-2xl">
                📆
              </div>
              <div>
                <h2 className="text-lg font-semibold text-amber-900">Yearly Report</h2>
                <p className="text-sm text-amber-600">Full year profit analysis</p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-amber-800 mb-2">Year</label>
                <input
                  type="number"
                  value={yearlyYear}
                  onChange={(e) => setYearlyYear(parseInt(e.target.value))}
                  className="w-full bg-white/80 border border-amber-200 rounded-xl p-2.5 text-gray-700 focus:ring-2 focus:ring-amber-300 focus:border-transparent transition"
                  min={2020}
                  max={2030}
                />
              </div>
              <button
                onClick={handleYearlyReport}
                disabled={loading}
                className="w-full bg-amber-500 hover:bg-amber-600 text-white px-6 py-2.5 rounded-xl font-medium disabled:bg-gray-300 transition-all duration-200 shadow-sm hover:shadow-md"
              >
                {loading ? 'Generating...' : '📥 Download Yearly Report'}
              </button>
            </div>
          </div>
        </div>
        </div>

        {/* Info Box */}
        <div className="bg-blue-50 border-2 border-blue-400 rounded-xl p-6">
          <h3 className="text-lg font-semibold text-blue-900 mb-2">📋 Comprehensive Report Features</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h4 className="font-semibold text-blue-800 mb-2">System Reports:</h4>
              <ul className="text-blue-700 space-y-1 list-disc list-inside text-sm">
                <li>Hub profits breakdown (Products, Swapping, Repairs)</li>
                <li>Sales analytics and performance metrics</li>
                <li>Inventory analysis and stock reports</li>
                <li>Customer insights and analytics</li>
                <li>Repair performance and item sales</li>
                <li>Pending resales and swap status</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-blue-800 mb-2">Profit Reports:</h4>
              <ul className="text-blue-700 space-y-1 list-disc list-inside text-sm">
                <li>Daily, weekly, monthly, and yearly analysis</li>
                <li>Revenue, costs, and profit margins</li>
                <li>Top performing items and categories</li>
                <li>Company branding and professional formatting</li>
                <li>PDF format ready to print or share</li>
                <li>Manager-only access for confidentiality</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProfitReports;

